accounts/urls.py
from django.urls import path


from . import views

app_name = 'accounts'

urlpatterns = [
    path('<int:pk>/profile/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('profile/', views.ProfileCreateView.as_view(), name='profile'),
    path('signup/', views.SignUpView.as_view(), name='signup')
]

chats/urls.py
from django.urls import path


from . import views

app_name = 'chats'

urlpatterns = [
    path('<int:pk>/comment/new/', views.CommentCreateView.as_view(), name='add_comment'),
    path('<int:pk>/', views.ChatDetailView.as_view(), name='chat_detail'),
    path('', views.ChatListView.as_view(), name='chat_list'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('chats.urls', namespace='chats')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    # location of the uploaded image will be in MEDIA_ROOT/images
    avatar = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.user.username

chats/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()


class Chat(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Comment(models.Model):
    text = models.TextField()
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


    def get_absolute_url(self):
        return reverse('chats:chat_detail', args=(self.chat_id,))

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('username', 'email')

accounts/views.py
from django.urls import reverse_lazy
from django.views import generic

from .forms import CustomUserCreationForm
from .models import Profile


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name= 'signup.html'


class ProfileCreateView(generic.CreateView):
    model = Profile
    template_name = 'profile_create.html'
    success_url = reverse_lazy('chats:chat_list')
    fields = ('bio', 'location', 'avatar',)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProfileDetailView(generic.DetailView):
    model = Profile
    template_name = 'profile_detail.html'

chats/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Chat, Comment


class ChatListView(generic.ListView):
    model = Chat


class ChatDetailView(generic.DetailView):
    model = Chat


class CommentCreateView(generic.CreateView):
    model = Comment
    fields = ('text',)

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.chat_id = self.kwargs['pk']
        return super().form_valid(form)

accounts/templates/base.html
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <div class='container'>
    {% block content %}
    {% endblock content %}
  </div>
</body>
</html>

accounts/templates/profile_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Create Profile Page</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-primary" type="submit">Save profile</button>
</form>
{% endblock content %}

accounts/templates/profile_detail.html
<div>{{ object.user }}</div>
<div>{{ object.bio }}</div>
<div>{{ object.location }}</div>
<img src="{{ object.avatar.url}}" alt="{{ avatar.user }}">

accounts/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class='btn btn-primary'>Sign up</button>
</form>
{% endblock content %}

chats/templates/chats/chat_detail.html
<div>{{object.name}}</div>

<form action="{% url 'chats:add_comment' object.id %}" method="post">
  {% csrf_token %}
  <input type="text" name='text'>
  <button>Add comment</button>
</form>

{% for comment in object.comment_set.all %}
<div>{{comment.text}}</div>
<span>{{comment.created_by}}</span>
{% endfor %}

chats/templates/chats/chat_list.html
<ul>
  {% for chat in object_list %}
  <li><a href="{% url 'chats:chat_detail' chat.id %}">{{chat.name}}</a></li>
{% endfor %}
</ul>